### ISSUE TITLE
Unit test add-on methods

### ISSUE THREAD

**Issue by dbouquin** [bsnacks000/IPySigma-Demo#17]
Test add-on methods that get injected into the nx.Graph class within IPySig
([L127-141](https://github.com/bsnacks000/IPySigma-Demo/blob/master/ipysig/sigma_addon_methods.py#L127-L141))- ipysig/sigma_addon_methods.py

**Comment by bsnacks000** [comment]
added basic unittests for sigma addons and fixed some bugs
